language: ruby
rbenv:
- 2.5.3
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: XPWbNw+lB+s+hHwYg9QXQxQUZWpSahUVpMm541FBBUcKlLhrudtX2twUVmBssiRcCiyE0qLfXH6Dtfhns2nGiWj9CHMan//4jb81wrWPF8Nb5tDIomhijCRgBNvnjWbE9S4MXslJmdHHptKG1Yb7YQT7pAhALKNakirQkKw4m7KdlCwe/Yqw3SAZ1HVCjZ2Rk4D4WtyJwKv/5HyD0CDgXB72s/DJDYrzhE0qxYj5c9WUQ7Ht1Tfre5Lzs/EPA5GpYBmJuH+T7nQXV7zzApMZHFH29xtePtuAl7WzVjHX9roV5oHDevDQP8ugTRYprK4tneVzyY2+I5vo/bLFiwFzluqkK8ovkfoCdbMYFvyCpkIyVROeOw0A8MDLb8r83Rc/fIyQ8x3Oh16mLBVbmVz2eBf1qOhKxz7W9AilwlvpRuJkN3zOAl/LpEXBwV/VUnkg02i+rCU8ziGPmvhMQpvl012qX7fwsee5M1zADrbkeS/GQ+Re4T0wmysbFk9p61/CllXkjUQp0KtqwczaNqIzE3H9U9WPOzYf8YUDpmHosD6AuI2/R09bXDU0XqhO885wPiJ4aOf60PFmThLJ8JhQScTjXYVtN31qLXeuHdGCWrL6rNktX/Qk7S7Whgv8FvZNnwYefSWTxq84fliOLu2sELxez1OuIjPKT/RA87uN+dE=
  app: plants-api-2006
  on:
    repo: My-Solar-Garden/plants_microservice
    branch: main
