language: ruby
rbenv:
- 2.5.3
script:
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: A3UtO7olg59Jylm6qpHWS3PMDSAdoq9I+PBUti/4TbttdZfGK9FolcZaGb9PuE5JoS1BC2ptYE0DHE4J37o2FE03q/J4GsCdjw4QBsly8y/GqAAdEGDc6UhVLG90WomoONFysH8SYZxPfjCmevqvBtBpXpUMFhI6PAqsMMxMhWHc7JmNTL4Qm2gIKSOVNU+PeVDWPExDZBJbvBrJTOG5PRGv4ExNxeI3sROqs8q0dPm78QOE+nHxUU7LysCKzc37qwzIcJjpNHgfpCO4PqANz+rWxaTKjPMwydw/KrL/XS1KwtIJh+QEaJ3uj0/ip3Qm3uc6EwEDL8wGFs/JVhRtiLuUQzDAmoq/gIoOAbA3Lm+0Q+XrYlUnGaidG27lL9tNHLGOjqpFQo1YMSi5+WTm7ykUExNd922zkVLRYTEo0MXSnaLXTGzK/6rV8I/laNVg6EceoWQJEYON3wJa1/F7PuHonrfIRDI2aawVH5G3FpqnMivgdXEzwUQqmmcg1v3p3uK3I+8SjM39aaP9xX02XFkAMfkNrsu+igXD5l1EbokMFp6DdW4n2NiEW8m8tYRIXwKD5l4q3hmtL552/tggWbHqvFWfT39+aUONvtPbxmP8+4hU3MmCgP2xhGo4E7D5bifCSeK8MHfRHAOdj7ZND+VAro0cw29uo3lLxsyftKI=
  app: plants-api-2006
  on:
    repo: My-Solar-Garden/plants_microservice
    branch: main
notifications:
  email:
    on_success: never
    on_failure: never
cache:
- bundler
